### ISSUE TITLE
Stars are not aligned

### ISSUE THREAD

**Issue by Zabalba** [jmattthew/HeirloomRottenTomatoes#6]
Not sure what else you need for this report.

![image](https://user-images.githubusercontent.com/4722953/50744991-b56d2700-11f5-11e9-93f0-5fb0259fe112.png)

**Comment by jmattthew** [comment]
Thanks for reporting.  Does the error persist if you change the rating?  Are you setting the rating with the widget that you circled or with widget that is below the list of reviews?

**Comment by Zabalba** [comment]
Yes, even if I change the rating in the highlighted area it persists.

Notice the ratings at the bottom in the example:

https://media.giphy.com/media/8PByjuk8uzT1Ljz2cD/giphy.gif

**Comment by jmattthew** [comment]
I just published another fix that might address this too.  It can take up to an hour for Google to push out the new version.  Type "chrome://extensions/" into the URL bar, then tap the "Update" button. 
Make sure that you see version "3.0.10" next to "Heirloom Rotten Tomatoes".  Please try again after you get the update, and let me know if the issue persists.

**Comment by Zabalba** [comment]
Maybe this will help
![image](https://user-images.githubusercontent.com/4722953/50816114-8df98580-12ed-11e9-95ae-6003010fb83c.png)

**Comment by jmattthew** [comment]
Thanks for this detail.  This one is a head scratcher!  The only way that I can reproduce what you're seeing is by changing the styling of one of the elements in the area of code that you've highlighted.  However, all of those elements' styles are hard-coded in the stylesheet.  When you change the rating, it doesn't change any of the styles, it moves the "i" tag.

My best guess for now is that some extension you have installed is overwriting one of those styles.  I'll see if I can find any other reason.

**Comment by Zabalba** [comment]
So I don't know if it is a clean test, but I went ahead and enabled your extension in incognito and made sure all other extensions were disabled. After logging in it seems the problem persists.

![image](https://user-images.githubusercontent.com/4722953/50875671-6e1e9c00-1397-11e9-9302-2407b50c58bf.png)

It's not that big of a deal. I can still select the stars, I just have to be very careful I don't select the wrong rating.

Also, interestingly, I can select half a star, or a full star on RT's star rating. Modifying that star did not alter the heirloom rating. However if I select a rating using heirloom stars, it also does not seem to modify RT's rating either.

I could have swore modifying one adjusts the other (at minimum full stars not half).

**Comment by jmattthew** [comment]
I figured it out!  Just published v3.0.11, which will fix the misaligned stars issue.  For some reason I couldn't reproduce until I put it in incognito mode myself.  Thanks for reporting.  I'm sure this impacted other users, so it really helps.

You're right - whenever you update a rating using the extension, it tries to update your RT account rating as well, and vice versa.  Try logging out of RT then logging back in.

**Comment by Zabalba** [comment]
Confirmed! 😄 

![image](https://user-images.githubusercontent.com/4722953/50941434-e302dc00-1452-11e9-84c0-8da4f7950c94.png)
